steps:
- name: "gcr.io/cloud-builders/kubectl"
  args: ['get', 'nodes']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
options:
  logging: CLOUD_LOGGING_ONLY
  workerPool:
    'projects/clgcporg2-119/locations/us-west1/workerPools/cicd-worker-pool'

