---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: node-app
description: Node Deployment Pipeline
serialPipeline:
  stages:
  - targetId: staging
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/clgcporg2-073/locations/us-west1/clusters/staging

##cmd
##gcloud deploy apply --file=clouddeploy.yaml --region us-west1  --project=clgcporg2-073
