steps:
#- name: "gcr.io/cloud-builders/kubectl"
#  args: ['get', 'nodes']
#  env:
#  - 'CLOUDSDK_COMPUTE_REGION=us-west1-b'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'shashank3656/build:$BUILD_ID', '.']
  
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'shashank3656/build:$BUILD_ID']
 
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=node-app
    --region=us-west1
    --source=./
    --images=shashank3656/build:$BUILD_ID

options:
  logging: CLOUD_LOGGING_ONLY
  workerPool:
    'projects/clgcporg2-136/locations/us-west1/workerPools/cicd-worker-pool'

